package com.model;

/**
 * TKeshi generated by MyEclipse Persistence Tools
 */

public class TKeshi implements java.io.Serializable
{

	// Fields

	private Integer keshiId;

	private String keshiAnme;

	private String keshiJianjie;

	private String del;
	
	private int keshixiayisheng;

	// Constructors

	/** default constructor */
	public TKeshi()
	{
	}

	/** full constructor */
	public TKeshi(String keshiAnme, String keshiJianjie, String del)
	{
		this.keshiAnme = keshiAnme;
		this.keshiJianjie = keshiJianjie;
		this.del = del;
	}

	// Property accessors

	public Integer getKeshiId()
	{
		return this.keshiId;
	}

	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

	public int getKeshixiayisheng()
	{
		return keshixiayisheng;
	}

	public void setKeshixiayisheng(int keshixiayisheng)
	{
		this.keshixiayisheng = keshixiayisheng;
	}

	public String getKeshiAnme()
	{
		return this.keshiAnme;
	}

	public void setKeshiAnme(String keshiAnme)
	{
		this.keshiAnme = keshiAnme;
	}

	public String getKeshiJianjie()
	{
		return this.keshiJianjie;
	}

	public void setKeshiJianjie(String keshiJianjie)
	{
		this.keshiJianjie = keshiJianjie;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}