package com.model;

/**
 * TYisheng generated by MyEclipse Persistence Tools
 */

public class TYisheng implements java.io.Serializable
{

	// Fields

	private Integer yishengId;

	private String yishengName;

	private String yishengSex;

	private String yishengAge;

	private String yishengJianjie;

	private Integer keshiId;

	private String del;
	
	private String keshiName;

	// Constructors

	/** default constructor */
	public TYisheng()
	{
	}

	/** full constructor */
	public TYisheng(String yishengName, String yishengSex, String yishengAge,
			String yishengJianjie, Integer keshiId, String del)
	{
		this.yishengName = yishengName;
		this.yishengSex = yishengSex;
		this.yishengAge = yishengAge;
		this.yishengJianjie = yishengJianjie;
		this.keshiId = keshiId;
		this.del = del;
	}

	// Property accessors

	public Integer getYishengId()
	{
		return this.yishengId;
	}

	public void setYishengId(Integer yishengId)
	{
		this.yishengId = yishengId;
	}

	public String getYishengName()
	{
		return this.yishengName;
	}

	public String getKeshiName()
	{
		return keshiName;
	}

	public void setKeshiName(String keshiName)
	{
		this.keshiName = keshiName;
	}

	public void setYishengName(String yishengName)
	{
		this.yishengName = yishengName;
	}

	public String getYishengSex()
	{
		return this.yishengSex;
	}

	public void setYishengSex(String yishengSex)
	{
		this.yishengSex = yishengSex;
	}

	public String getYishengAge()
	{
		return this.yishengAge;
	}

	public void setYishengAge(String yishengAge)
	{
		this.yishengAge = yishengAge;
	}

	public String getYishengJianjie()
	{
		return this.yishengJianjie;
	}

	public void setYishengJianjie(String yishengJianjie)
	{
		this.yishengJianjie = yishengJianjie;
	}

	public Integer getKeshiId()
	{
		return this.keshiId;
	}

	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}